# Generated by Django 4.1.5 on 2023-04-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasemployee',
            name='Session',
            field=models.CharField(default='libWvEPKxpeOLuDOfTTJipFWaWHhyNOje3AnHWbt-JO3C6Rog2weFm_PztW2zk7EDXA0NCM0In6aM0YyBAjIq3EP-CbU92GOulFODN9W2r7oVS7DXEn8kPyfbJ2PiJOZoVwvdQ', max_length=150),
        ),
        migrations.AddField(
            model_name='headarea',
            name='Session',
            field=models.CharField(default='zfp_wjIco9W2qf7SoDBU8ZTAp_8HGCXLlo_-JCsNUUTv-wKpvK4CPg_lVLiIDauM33HiZEiTTLHEZhPUkMfOnhG2a5S0ebYfEv9nAOGn3B1It3wUxwxVqZueIrUTccyWOiQifw', max_length=150),
        ),
        migrations.AddField(
            model_name='headcity',
            name='Session',
            field=models.CharField(default='eysQ0-LGCG4GwdLSynx8JkwDiC29Go_vw7gBitIqywzLPE0FaLiHn6b-jkV7gCnkqo79OjrN9ZgP6XyvK6ckJ7Z5EwsMKLJ7xw3KpRtbYrVgHnltn-Yree823ROTX6UMQF-VQA', max_length=150),
        ),
        migrations.AddField(
            model_name='headrelief',
            name='Session',
            field=models.CharField(default='B6u_80pWKRThrkmpU91OvbYkspqfOXbb0NTArSlSJXqn8O94LGulA--Q75cTKGFlJWOlQ8051s0GQ4esBj75R_sXsTF8EDp1YP20o1SGq7m2UY2cls7F9KQeLKquYpwoLfL_mw', max_length=150),
        ),
        migrations.AddField(
            model_name='representative',
            name='Session',
            field=models.CharField(default='oR1Kr5NU_u-K-LfkSnxjeG0Wnz9P1EtzBE98sacZI6rMqSTeMIzGj0F7ehMT74Sh28uXzeZkQ-IPgSWu1dIph_LB1ym4Wjt7Qm2QQVzKlb_WtvTzKwzd5zRAgoBi9Ze8mNmGOA', max_length=150),
        ),
        migrations.AddField(
            model_name='rescuer',
            name='Session',
            field=models.CharField(default='HxM5NOhLO-uwpNeuMedFk1HWQCsQnpk0HSqQA0jsKksK9me5VedShbxS-ftF_UTR09EgjxN5PTSwufYI2G5v6-xcnXb-Ta95li7QzUqXHYFWnAK2gKnfQmaxR0MutrrQCW542w', max_length=150),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-27 15:47:22.304230'),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-27 15:47:22.306233'),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-27 15:47:22.305237'),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-27 15:47:22.306233'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-27 15:47:22.305237'),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-27 15:47:22.305237'),
        ),
    ]
