# Generated by Django 4.1.5 on 2023-04-17 07:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gasemployee_password_gasemployee_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(default=api.models.getRandomInt)),
                ('PeCode', models.IntegerField()),
                ('MCode', models.IntegerField()),
                ('StartTime', models.DateTimeField(blank=True, null=True)),
                ('Duration', models.IntegerField(default=0)),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 11:41:08.473082'),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='Session',
            field=models.CharField(default='ZhgCn3_6nXHjILOIXYq3xqDufQjoxSMIONGSu8jkMIJ3YY_YXy0c9hiJo07qSyLFzOl7c5OIEN2lGIG0VGJwOCwDTKFNXUrDbST_oNXj1k8bbvIWZuAXAbEvFmxAeBC4URtv-w', max_length=150),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 11:41:08.474080'),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='Session',
            field=models.CharField(default='WnluUMz7DJ0ef1nqEP2XaP127d1IE4xKRPFeogGLPsW7NSCTzof-UfED0foLY49Sgyp2pWlP0YzFRbuOE5XjDpYLrpi-gu3SmHj_0rUU8mSQTIZrpJQheXjahuKhhs1lX4-y4g', max_length=150),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 11:41:08.474080'),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='Session',
            field=models.CharField(default='SfdDvxVHywSbQd_CoLrJrZJUnq5hEV7z5kzxhfyg0AVpBYZRHStycjd_WcDRrWvYnRY8wk1NhGLDHDzfXNrMqDm3zijKfwESq5yozq9UQNxckXmQ7yK50mQzsEnU7GaKbqivyw', max_length=150),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 11:41:08.474080'),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='Session',
            field=models.CharField(default='MuisF6fClEAOPc63ru8GLFwtUoAX5_lKH4LA2r97kmyycH-z_K7DVRa9h7HabOnr8sjlnDW_q1GAYK5bHmsqx1x0AkAEbOFSr3Iff_aKmh6a2xUrMeIhEzEV56_oTzGGjOMNhg', max_length=150),
        ),
        migrations.AlterField(
            model_name='representative',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 11:41:08.473082'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='Session',
            field=models.CharField(default='WppG2kuF2tMt4dicDuH4UGoVSieObLQjzvSksiHgPWSVojonjS64aNKAXG0NE-yAF5XR2GxzIoiDEmzKYsqs77HZgfVAUZZwp42ZlV5yja2czQyaB34ziiMYn9QcreZR0v8j-Q', max_length=150),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 11:41:08.474080'),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='Session',
            field=models.CharField(default='kyUvo6bwOiBUjz6xozLGB-nqe2Zo_q0Cs7ShzZzBzKLLSFf9SkK7MfO5OfU_YiqXCYdlufHl90y41i-o-fmLCrpz9mO16pfL-QkkmDUzZlPg17-AEUTOWoWXOZa1hnn1vlg7gw', max_length=150),
        ),
    ]
