# Generated by Django 4.1.5 on 2023-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_request_alter_gasemployee_registertime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasemployee',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 11:41:12.980029'),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='Session',
            field=models.CharField(default='pUNmJlj1s9nBm3wN6HIR_Y_JOwYFFs282PXiBIfEol4AIvOffvgY7F9YBqu1fN4LrBM8YYxBiJYV1ND8otgaXWpE1YPMBFeM__A6H2RhHRfiS456QhdW8iHPhv5hZnYe_PkO-w', max_length=150),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 11:41:12.982009'),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='Session',
            field=models.CharField(default='S1Tr0wRcHxXvGSRS8aVIzkvf3i5czKHs1HIIVU-4vlwALdNE8gsYxVT8QHaDU9LX3GUe1RuWhUR5lJi4awaP9e_7KYCbvcAkpfC_RQC4rNhNlDVUeV9rQ95C3Ib2ah16ZZtbXw', max_length=150),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 11:41:12.981021'),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='Session',
            field=models.CharField(default='fs-9S5wSBLak3iU--njr6FIWkh7Jp9FMibS3cYSYzjQDk6nIvDFfeec0t8ThaTN4aMtzXmzxBVniv8seoLPESZCpf4WG5YZRqViVqYf3t3oSYhtELNnB-DP6vKymSRrgmgIqsw', max_length=150),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 11:41:12.981021'),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='Session',
            field=models.CharField(default='U3d2z0cAamDpTgaEbpoaMpSd1gyNhoT2rJ1vSuCeoH1wOsyQvfywGgCOolWhZ_IuDbH1WzQlyEky72hvbih06pc67nC7-EQ9FS6g-oYtrsL4VaHTf09kCgBNiAWOssq-MKg5Mw', max_length=150),
        ),
        migrations.AlterField(
            model_name='representative',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 11:41:12.980029'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='Session',
            field=models.CharField(default='mQ9Fcu5g0Tpf51DhDdaKAwuiVKs80Vge7Jmwz9V_ZLhCt2XNmECwdFncLSwHNx3MmjaWJK7LYSVt9l_hNeK6xxCVNh2oWuD-ZKgwTDWdKOsrde1OxizdXwoJi6c9DdaIE_AT2w', max_length=150),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 11:41:12.981021'),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='Session',
            field=models.CharField(default='O-dRToQQ8X1mHXDYcqqV-YkBgHroAzT3PMK0fHTFHdfdfTpfJOqNEkymIciNRhrA0fI_u8cb2g_R5KCQKQPQCW_F7PElcs0gXu1guKG5fb-CI4lsdAjkO26qp8_UlkDb5y4fQA', max_length=150),
        ),
    ]
