# Generated by Django 4.1.5 on 2023-04-17 08:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_gasemployee_registertime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(default=api.models.getRandomInt)),
                ('PeCode', models.IntegerField()),
                ('MCode', models.IntegerField()),
                ('Duration', models.IntegerField(default=0)),
                ('FConf', models.BooleanField(default=False)),
                ('SConf', models.BooleanField(blank=True, default=None, null=True)),
                ('TConf', models.BooleanField(blank=True, default=None, null=True)),
                ('StartTime', models.DateTimeField(blank=True, null=True)),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField(default=api.models.getRandomInt)),
                ('PeCode', models.IntegerField()),
                ('MCode', models.IntegerField()),
                ('Duration', models.IntegerField(default=0)),
                ('FConf', models.BooleanField(default=False)),
                ('SConf', models.BooleanField(blank=True, default=None, null=True)),
                ('StartTime', models.DateTimeField(blank=True, null=True)),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 12:40:56.440325'),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='Session',
            field=models.CharField(default='N2QDCN_vGOaHxPEBL3GCkrGU26RnatZdRYZWwn5rOpUOEHXmqdU2Ezr2aCB6diXGLUBEQieetsuss80t5OsioBy5wbwkg0CJRWQencKt2yg9__KGwR1nRbxwBxGWq85mhHblrA', max_length=150),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 12:40:56.442326'),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='Session',
            field=models.CharField(default='sFUeW8S0d7XH29xSkFMyeMgb0XJMjxW-sLt1L7bORmuN-Jf2dMO_ndLDpnvRym9tI8DU_a_F6wWTlxdywY1RP7835mqUK2dECOcil10To5BPnhsQv5Qq7ofD74TgGyZ57Uq4Iw', max_length=150),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 12:40:56.441332'),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='Session',
            field=models.CharField(default='PBO7QrCyebxX75tqGbjdz1MuNLMzYMqPiGe-WUfeHh2QYPOdwAmrLLqMn87zScXuPY9v6wqaHQ2yYsK2b-HVy34pi9zhRrhTpvalk_JNuQ2mp-xE6S71p0jxL5K1mxsqDmQznA', max_length=150),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 12:40:56.442326'),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='Session',
            field=models.CharField(default='bU2STa6RDu02Z3mt2lqvuQJI6LQXAZwFGsedq-nNBEmP4uBZZbyCarxDDuJjiv0kTzxZOxgtdbxiIcQg8HIxq5Nfxmd_EyLIGUQGOlbITYT-B_k10Wx11h6PbM-YHtbaE3oJNA', max_length=150),
        ),
        migrations.AlterField(
            model_name='representative',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 12:40:56.441332'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='Session',
            field=models.CharField(default='V0kCQs8wdqwwfiyFaFRxxEkCtPs1CRje5khJw6E8Ovz2AnQRALMwuMkXbFA8sWEah92TQrnwWuzEeYUo8wk7l5Ya-eH2PU11zyY4WTY18j5eyF-mzDpVXtHMWQMSG0n-FEja8g', max_length=150),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-28 12:40:56.441332'),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='Session',
            field=models.CharField(default='mc0hEo-QUvxmT0-uUQgR0DZ4yn5-mvamQEMxDroIlNL6nUDkozldHXNSAhjNxK3iwcrJKc3POnHT8mULcSMgsvcVaFPUSblOFN8NdgMSjKpk8_i4AB0Qrr1VK4GO0WxQ6crJhw', max_length=150),
        ),
    ]
