# Generated by Django 4.1.5 on 2023-04-19 09:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dailyrequest_hourlyrequest_delete_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrequest',
            old_name='EndTime',
            new_name='ConfirmTime',
        ),
        migrations.RemoveField(
            model_name='dailyrequest',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='dailyrequest',
            name='StartTime',
        ),
        migrations.AddField(
            model_name='dailyrequest',
            name='RegisterTime',
            field=models.DateTimeField(default=api.models.getDateTime),
        ),
        migrations.AddField(
            model_name='hourlyrequest',
            name='RegisterTime',
            field=models.DateTimeField(default=api.models.getDateTime),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='RegisterTime',
            field=models.DateTimeField(default=api.models.getDateTime),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='Session',
            field=models.CharField(default='hL4SVAnbmgCm91Moj1XvwvckWUbScs2ESj4-Y0mJZCWJONUcDV-pCUyjOrLzI2BU5OTodSq7-5VoipEJl85vsCczYOlaQNPexZjQ43GkwfikXpBLF1MNtZBc1cGd10SvBMcG8g', max_length=150),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:03:55.400723'),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='Session',
            field=models.CharField(default='ZKD2bzYtlH_tueI9ZVr7LXAuHKowWNeRnl8s3lEC9c766yEwZmSLJ73tSYX-Z-pNXL6BKhBLv9eMVZwHdA9f9sP4E5rwFBAmuCNJGP3s_AcLPz56DTZlY22DT_ybBHqKfdlAjA', max_length=150),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:03:55.399726'),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='Session',
            field=models.CharField(default='7ilaqDkTrUs3ciOqVfLUNclyazgTtNZoTOZ781Mf-oIQkbxs5k7Q7UPKQTQux5L__KX32tkjzeNUqkzrSCTFkn9DXTPwvj2j_31rPkAT92uEuScKQ5W6_1HoGzMBBEehjTmIPA', max_length=150),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:03:55.399726'),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='Session',
            field=models.CharField(default='MPgLp9oWIF1ITThsdVCANKjzOnBUjYW54cMeQyHSy2KHrkh8-DlauPOt2W268IVdxqwkwRO0lw1fr2paCuUBC4n4k5XKfkno3DSnRv2CL-p4LwupTBQNUumA23JkXdjiQToarQ', max_length=150),
        ),
        migrations.AlterField(
            model_name='representative',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:03:55.398721'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='Session',
            field=models.CharField(default='LYbCr8ZoiQasPWyap_Q1lJZXA8TYxA9vwL6UsR8czev29Zr-3fm-zBO-DaPkcY3EpwfW0HGfdQsrgmivk4sm9hWGwIU4otOWDmhZaCfQVHIkF42HxWCW7rpJB3oqexQHHC3JFg', max_length=150),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:03:55.399726'),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='Session',
            field=models.CharField(default='JsbwqEKytZoRIAO5N5uHb2cxcSmvzGYUsbncZyt19YCYfhcbGom1PmE3C6YBJrr6QQEV1TZ_xeqpp0Vu9EQKaaH5cje0ZyUb870kQABeGrZU6ugXHUAgU1m2VE8do9VPnssc9Q', max_length=150),
        ),
    ]
