# Generated by Django 4.1.5 on 2023-04-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_endtime_dailyrequest_confirmtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrequest',
            name='Status',
            field=models.CharField(choices=[('WaitAccept', 'WaitAccept'), ('Accepted', 'Accepted'), ('RejectFConf', 'RejectFConf'), ('RejectSConf', 'RejectSConf'), ('RejectTConf', 'RejectTConf')], default='WaitAccept', max_length=30),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='Session',
            field=models.CharField(default='pTG6Dfj-AT5ByeQf4lFjqW6KxQGPksrhL4-fZVnCc0bn8sMq3kYH3vayaVUnnaJsFvPsU-3VoGl87JypRMLUojHp--Ar8gaIyWZfkqRe-67JzgGE7sht133W3K_lK6g2bGLKMQ', max_length=150),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:51:34.910595'),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='Session',
            field=models.CharField(default='m5IJGokrpWw53S_2TEpNtTreYntfq9DnEt0m7dNHF2BGLqfQRRMXRetMMi0FdH-HlMSHkBy5RO1U6niSCdtiWEX6xhdo5HiNLi91Aqcxln9Sxso70DRcixXQ4ZghG8p9W93kxg', max_length=150),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:51:34.910595'),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='Session',
            field=models.CharField(default='hcOxUh4_Scus2Jw0IWPg56aBAlNPL3nfqXmGU3YVk8aXX2wLtFy7vn4Ew7e7C8SzXBy6Gy-wfMEt4HGaDOxuAsRCV4a_NIj4iWKrgLNfWwj3Pv67JtNuwJw_Wom6SBnF0iuOPA', max_length=150),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:51:34.910595'),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='Session',
            field=models.CharField(default='44BGoeX-MhVIMT4dvkQ6xKS2qjqi8ZZ_4qMVA9H4zy5OIDlBfQjwrjCMohGXGiylvIHOyG0UnCftxms2mWTOTebpGf-hq4p37-UiirsN7cw8zG9CrcQUeatvuxemVPL61EVzFA', max_length=150),
        ),
        migrations.AlterField(
            model_name='representative',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:51:34.909598'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='Session',
            field=models.CharField(default='cMKe_XRZ0uQVEmXLBNye5fc2y8OVPJ4dUfDiiK4bWqI5SZfwmizl4qRLLzNsrE6M6JYxhLVFr4dwXPvftxcen547zlmADuG5FW_Xs6uvKnc5WPYMw7yxg_fn5-zy1-ljmpuEhw', max_length=150),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:51:34.909598'),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='Session',
            field=models.CharField(default='pKHq2Zv-bW17VFOmVz3cX4KTCGNXV-iazCCNGuu7cCK-SAtJ3iR7TmNc9yTn2VP94R-8ho_7wXR-B4dSfGOmd5KmYLTCKAQgwioTCZGnr9sKyLM6cFZRTOBhIxC03q_fj7vxgQ', max_length=150),
        ),
    ]
