# Generated by Django 4.1.5 on 2023-04-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dailyrequest_status_alter_gasemployee_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyrequest',
            name='Status',
            field=models.CharField(choices=[('WaitAccept', 'WaitAccept'), ('Accepted', 'Accepted'), ('RejectFConf', 'RejectFConf'), ('RejectSConf', 'RejectSConf')], default='WaitAccept', max_length=30),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='Session',
            field=models.CharField(default='laRMg7SMnjNvC4Md0GZKBE1Ddp2hRPyHpRQQaHdvT-Ll6oPdVqFWrtZPzvD62CXojcNapHgrtQf3UJu3jcovLwvcaIQTwCybYlm38wDGv6n1xx6RI7_qpwqlLVVom50DkRB_fg', max_length=150),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:52:55.27342'),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='Session',
            field=models.CharField(default='cct0-VHbU0vutNp46JPKAziUmRvQMEGvbV9efFLW86WYR1qcOwLK50HSRPe-ERQK3UOzmMrw2EWrlmFIRLPDgk6dfKef-n_593SI5PHFMb2sigZIlgwYRUJFKJ_edeHrJ5ljLg', max_length=150),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:52:55.27342'),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='Session',
            field=models.CharField(default='hCtNKOCv97JBQAabrb5L6B9TGV2BrBElGqLO2yCaU4SfMtFWRMQML6DuTXKVYn37PQbvnJkcwg_nsOrfFy1vqag0fJiNZ0IP5XpZ9cANl8EHrowJ7Ey92ErtnhzohvA79uDwMg', max_length=150),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:52:55.27342'),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='Session',
            field=models.CharField(default='NhOiVRP1R6atdXWInc2yr0leX3ikmJ9YHmC7IEfvNHfybspL6YbK7e8fvJ0i6M1tIBZ1AgQ6xwk0OhBj3_65r53YdsTt89XmLYd_tBX_5J3GwHJTis9P5shuoKX5jMxy0RFDLw', max_length=150),
        ),
        migrations.AlterField(
            model_name='representative',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:52:55.26345'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='Session',
            field=models.CharField(default='uVHEcQ8aMkil0Jo6pYFcZKMdR7Ee1mpgeGpaR7R38LnWy9MiEdBXYkgyTsjT3IGD2PhErjGisB9qnmGV1x9k_Ljsvt0b4P6PqTcL08u0lmF-UGx7fHPECppqZw_fQ9Rma93euw', max_length=150),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='RegisterTime',
            field=models.DateTimeField(default='1402-01-30 14:52:55.27342'),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='Session',
            field=models.CharField(default='qRAjiTtzteNFyPPpBpj8z1rEcXXvSrUqJzyHAzf5faCOMivIlIlosd3NOeFNylSPF4XoMWQomXtBV0XvKPWEhJ8sFo6WlZVb2bhZgJgXmC27E1wAZb7-QGmTl3vwzLZ1uVi5hA', max_length=150),
        ),
    ]
