# Generated by Django 4.2.1 on 2023-05-20 12:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_gasemployee_listofmgasemployee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasemployee',
            name='ListOfMGasEmployee',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[0], size=10),
        ),
        migrations.AddField(
            model_name='gasemployee',
            name='ListOfPhone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[0], size=10),
        ),
        migrations.AddField(
            model_name='gasemployee',
            name='ListOfVillages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[0], size=10),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='Session',
            field=models.CharField(default='cj3MWFltdJCk3xkz1lfXFWUTjAh56fOntyC4zMKJdpZ3PPlZN4e1_nvF22cdDDbnpd9b223gzCPVNpI2wfu5uDOIBqt72fvzb83haeKKcNhTetLsTCiA3cqlccqyXR21hThqyA', max_length=150),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 12:59:03.067889+00:00'),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='Session',
            field=models.CharField(default='wR0ulUu5bpJxuxPA2Q2wq3Xbc2GwtdWkgTIOyLN5nejkhUwg-oXsg86oj9ITZ_nmSUH6lfE5L0ie_JhTnQN7mtqHo3EtsAMLsy8Z-6GcB36Ca6qebEAKqFS46A89SxPsQGM3YQ', max_length=150),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 12:59:03.066889+00:00'),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='Session',
            field=models.CharField(default='i5MJISlYEdEUEKcyQC_8O3H0ZMDyObk78tPpTzqsZSDQq0m_a75VLUUhaJ4rxdNFliNXio86Fx14Ubg4ntjd5UC7W_e-Mds6H_fwepXVIy8tVa3pjSF1S9Nd2tYRNjPA7kAD9w', max_length=150),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 12:59:03.066889+00:00'),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='Session',
            field=models.CharField(default='zcjgPdW99XaiiZPbEqCofcwv03Y5vG-sgxBPN1dEysnAzEjBijMXbUDzKyc8CaBxW3B5ENxydBLYfkQQfChZgcS9kCKN1MFWgE-HbKfoGGFiHAWaPmrrPyHEjc5qN87iM1L_Ng', max_length=150),
        ),
        migrations.AlterField(
            model_name='representative',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 12:59:03.066889+00:00'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='Session',
            field=models.CharField(default='GOsxlA04WvUk0tYMy8KK957hs7dE8DxwlxuYw__0FxRQpLq71KCsUbqAmuJXXEw8TCGZwxvHN95fNKKDlSMbNXC0fPf2e-0wME9dKW7qwWUPfSSq5ExTk_i0eWxNUlpLp5JQWA', max_length=150),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 12:59:03.066889+00:00'),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='Session',
            field=models.CharField(default='zw6jrg0jGgP-QPE2UL8ZKSICaz7gB60CyfUukI2-SP6rlJcAggJO1pg_U9yYxlwk4ck9cekhbVaKtOJ2F-MdElPlBh9zW_luJBgPD8xwvd5Emg61je4GybzeCl7H1z4o1sTNNA', max_length=150),
        ),
    ]
