# Generated by Django 4.2.1 on 2023-05-20 13:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_gasemployee_listofmgasemployee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasemployee',
            name='ListOfMGasEmployee',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=10),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='ListOfPhone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=10),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='ListOfVillages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=10),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='Session',
            field=models.CharField(default='aGdzpGzSMLeKzi3Clojk7dfoZLfJMMUxkvBmlD6REKSG4AqRE4GoO90WP0KJD-hJrATRNjhWTGtOWek1_hAKOAptzJCO7kYCqMhjBDmBrW33_xP7jioquLnB7JAqLzQfSyTKsg', max_length=150),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:01:37.411841+00:00'),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='Session',
            field=models.CharField(default='Du_QZbGtw3HPWbvrKRvkp3GlPSjrOEBSt7YtbEkrUUUTv1Jz364kqgimvVnK-onhd1n-I4zdM1-mGUHw7czu4ECYi64ljjyD41JsIl3YPhBHPCMOYrPfUyge5xmNjfQMBmRFfg', max_length=150),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:01:37.410842+00:00'),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='Session',
            field=models.CharField(default='vOe6LcXFQpdDm1Az4Khl4JxYHn-FmvUxBvT1KSC0FMxVmK98s1-UiWm9MpTIi7ojldGi9TRtv5RyptA7vj34KEDr0rpbG4sXuvz17XgZPFhkiEwAOyVAYb9oHHfoj-NpycjPqw', max_length=150),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:01:37.410842+00:00'),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='Session',
            field=models.CharField(default='9lEVvfXjPaLMGgsnY3qMsVm0vRq1maTa2D4XOxBcuV19J1z5MyfhDari4FMcZujxOiVuA7XVcsm69lj2UPyHwmumWqAq_W-ia9ghoOF2TghOAXUnCbLRjnhGEZQzyi0Ne5za_A', max_length=150),
        ),
        migrations.AlterField(
            model_name='representative',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:01:37.410842+00:00'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='Session',
            field=models.CharField(default='Pp8KUU-hqEN39QmqeNlyWtSNntBn4itAd66b5QCWFz_rkGYa-63BlNR39IT5xuPUe1TxjWar6CmjR6nqgFFCYDBQJG5rKIm6pUVQoB92FKHhXXXJ1zEMOw1qXoKpRgnxjtjAhA', max_length=150),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:01:37.410842+00:00'),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='Session',
            field=models.CharField(default='fvzjuxWHr7oSqYBEN3LExiTBak7pgb6irI_da7wnz1OhhRb-QqUS3cqJIMVQhkdJNeThntYNuqC1PPRm8MrkbMu_92-kSFpJFvPHw7xFQCdYQMHMdjUWA6-eVz369fHEKeDDTQ', max_length=150),
        ),
    ]
