# Generated by Django 4.2.1 on 2023-05-20 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_hourlyrequest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasemployee',
            name='ListOfPhone',
        ),
        migrations.RemoveField(
            model_name='headarea',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='headcity',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='headrelief',
            name='ListOfPhone',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='Phone',
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='ListOfVillages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=30),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='Session',
            field=models.CharField(default='MsdmyMRcYKGbbmCp9fzJp2aMntzCJntmN0WsnLHIiF9R1zWry5V3tL889dzOD3F6Bp2_-IMotzeMu1d2-ZMYkHbiHyKb4Tu2yPk_hlNCIXr6T2p_k6H4XYC1GW_gOfk1KtpIHg', max_length=150),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:10:09.140367+00:00'),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='Session',
            field=models.CharField(default='_bCRjBCSYkH1lJ6sC4LJMraAFSigjBnJp8fDbl0jO6aFTxQ9hE2Lvm_QmIxY2iztojLi2ZzrpqDPEpgDmrKE9s7tCk3CZx7FvQqaXxqHX2hSRFkNKnp4WnRVV2I4nP9ks-eAhQ', max_length=150),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:10:09.140367+00:00'),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='Session',
            field=models.CharField(default='qdvrmidFGNQwh2ixqWnQDYWn2CAs350PKsp4dLegYV7OUbkAH2fBLLQWQjQOfD_Vx2VmdyLvuV2hS4lpdUkSf0rMvP16SohsypLIpoM4HP3iH-CWEU-63IkJAC1X0jMnhXQ7mA', max_length=150),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:10:09.140367+00:00'),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='Session',
            field=models.CharField(default='qSOcMIkeEg5OCInTSnVIlNvrYJea6ZJp7AJ9L1GPGtz0JS7YpBziuBp14GB5TyTNt_PL0DsK6NjQBYaRE5qh0OVTKg7XvPpkYBeCMAjMCXmtM-04J4wdfoeA1Ox6h9NW-uyNMA', max_length=150),
        ),
        migrations.AlterField(
            model_name='representative',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:10:09.139367+00:00'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='Session',
            field=models.CharField(default='-egUllff4TzgxdRCMJnF52xsTvuRkmiPCPVKQNpeyYVqlc2PV58QKxCM9dCMrO9YgXcnCwF1uK0RMRFplGea5_CEYEt3MxF9LS-8M1xUVHskSpyZFO71BMcpYXgDeoP9RNyepQ', max_length=150),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:10:09.139367+00:00'),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='Session',
            field=models.CharField(default='P0z2DPSdimKfMJu1XZRiNsMVTWfhikvh5HdYEgPafqAqjnjXrqedLg8CnxVW8LpkXo_W6_jK_nH0E_vRpEQ6t9yiYrBa8aTn-I9l1LYkFFjY4OeCVEGYg-996sBRl-teNq39sw', max_length=150),
        ),
    ]
