# Generated by Django 4.2.1 on 2023-05-20 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_gasemployee_listofphone_remove_headarea_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasemployee',
            name='ListOfPhone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), default=list, size=10),
        ),
        migrations.AddField(
            model_name='headarea',
            name='ListOfPhone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), default=list, size=10),
        ),
        migrations.AddField(
            model_name='headcity',
            name='ListOfPhone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), default=list, size=10),
        ),
        migrations.AddField(
            model_name='headrelief',
            name='ListOfPhone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), default=list, size=10),
        ),
        migrations.AddField(
            model_name='representative',
            name='ListOfPhone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), default=list, size=10),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='Session',
            field=models.CharField(default='jdQDisi6dx6Q7Z2r2Gbj17k6XTzLX1Ph8gKd0niBoA3wZMsEYeQjqVcQDixlRUVg0v60MQNlPtVcO0bSiMUdSVz-nIS3mIyyZmumNP6D0rRNqmCCeTe8s17h0AbrybN_V7B00Q', max_length=150),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:10:38.811964+00:00'),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='Session',
            field=models.CharField(default='1DCHJwDdOwh0Zad7JPPwAIyobHouoY0epeOz-LhrTUEAxvW0b0PjpmV9tE2pKnKJSmWQ8asPepENu4r_z_Cdwz9Vt-awigbjLaKqY9RNptqsIv3Wgwo6jOyniSuvlYgxicJ-_g', max_length=150),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:10:38.810964+00:00'),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='Session',
            field=models.CharField(default='SN4Ql0sK37pVXenEmjyK7Z5rqU7XfLNMELGdFHWfA3uzhb3M9fq6yq_j9aGy_1oMwMTQndmCFhQcEXA_ypyZAPS3VlO9HVBdfjyNT26oyK7AMboGrN-NU2io0kNKWOPmLVkmAA', max_length=150),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:10:38.810964+00:00'),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='Session',
            field=models.CharField(default='Dpr4bgIQhBSIcfo0g5vw4E4np6eN9sqmEjZktUM7ib4A10g-Wk-KcUjyuOHF_e2oAO46B0k4xSvrtSZF9wfRfIcAwcOU8DeSXqFze2OjZys4ukSN0AdvTybIgbpAK0p4iQQjHA', max_length=150),
        ),
        migrations.AlterField(
            model_name='representative',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:10:38.809956+00:00'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='Session',
            field=models.CharField(default='c8bLnwEOyTu8U7kr34fa2ZJV-1V24-oGxZf-IvcElwEgrMaQb5yTOE0QjvBk6vYCMXg63qwqa8tgQNzmDfb55b7gywGlbBFAlZ73QPrae9nqM2bNxQke-O4J25hRW7Bzw4Rr2Q', max_length=150),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='RegisterTime',
            field=models.DateTimeField(default='2023-05-20 13:10:38.810964+00:00'),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='Session',
            field=models.CharField(default='snX-yDFpn5UTmRL6z23ZbQN662fITfMVR-nwBBB19T0hvLr8YCtt1AbVEpsVCRnWxDapfQ6esUXjMbzS2DRAaJ4rqgS7hIjYEjL6MZ5DIMCyDgVRjwyc3qF20yV-iHNUCgSy8g', max_length=150),
        ),
    ]
