# Generated by Django 4.2.1 on 2023-05-24 05:38

import api.models
import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_headrelief_citycode_headrelief_listofcity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrequest',
            name='ConfirmTime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrequest',
            name='RegisterTime',
            field=django_jalali.db.models.jDateTimeField(default=api.models.getDateTime),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='RegisterTime',
            field=django_jalali.db.models.jDateTimeField(default=api.models.getDateTime),
        ),
        migrations.AlterField(
            model_name='gasemployee',
            name='Session',
            field=models.CharField(default='6fbILGqTpmO28ufZSrC-CAjd7SgBEgVdtxUNT-2Pq3jH26lg8COMQ1PcdvA5GzhNCLQuyV--1Ip5wYTV37u12UjcM_rAY4GkDkgYxfQDq8eYygO6i9OBOSSc6uGQIVPN7Q0M6w', max_length=150),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='RegisterTime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 5, 24, 5, 38, 59, 401563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headarea',
            name='Session',
            field=models.CharField(default='fe0F8g6ybY71waxCl2JkhB4i2EPnBoQLtg-mhLg42_A2ani19Sh6h4aQZR7xy3cnGTTC8n10sU1bRtkY6mVSGvIB9famjn1ukdSiEFIx3J_qU9VBrzOAjsWZ73xdqwfKbfCHKg', max_length=150),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='RegisterTime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 5, 24, 5, 38, 59, 401563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headcity',
            name='Session',
            field=models.CharField(default='1T2z4mraqCFVa-RjdCdKTvTl3JHGIGwc7VPVvVHgNdmIxJXV3COo1EtWJZGkJVxXfUS-5UiyoMzkYxyo_0lYLSwXA0ffBlgd8OqJ6k1gWBkTPn7lVR_wdVbibA8SagJHAN933Q', max_length=150),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='RegisterTime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 5, 24, 5, 38, 59, 401563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headrelief',
            name='Session',
            field=models.CharField(default='qlUi2XX9dg_g6dpmk2P56IAd9EXMrpYRW_7i3E9U3f1KNIL8emUo4cFe6tPkvd4FSs0LxK3DP_4XxZ9v95KNRNn6meKB7jwkPTqfIgJJyTZSN4aXS2plHQ6r2HDwP4S2HhyBag', max_length=150),
        ),
        migrations.AlterField(
            model_name='hourlyrequest',
            name='EndTime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourlyrequest',
            name='RegisterTime',
            field=django_jalali.db.models.jDateTimeField(default=api.models.getDateTime),
        ),
        migrations.AlterField(
            model_name='hourlyrequest',
            name='StartTime',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='RegisterTime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 5, 24, 5, 38, 59, 401563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='representative',
            name='Session',
            field=models.CharField(default='5jzZiVRBI14JsqzcGetSj6oy85sGmG7MdHClFazcJEbGvt2R8OvAsiE_YsQTGUVGX0pEGfJEvVspjngtCvIhYZdTYhVIKpA_u1WjMoBPjroww2YIict8aKwcmEKJB1clLMM7-Q', max_length=150),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='RegisterTime',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 5, 24, 5, 38, 59, 401563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rescuer',
            name='Session',
            field=models.CharField(default='3zLXAnJh8Plm6pSbuXSoDVGmhFkNUy2A6UoAIOXJp6M3Q9hzU8iajTPVxT10YxP5ne6L0RkMLzDjG8OIXxNWdtQB6srMdlDaAlo9R3uRLvsx1RvuHP51jF5G5QXX8hX-gn6bGw', max_length=150),
        ),
    ]
