name: gazban

description: A new Flutter project.

publish_to: 'none'

version: 0.1.1



environment:
  sdk: '>=2.19.4 <3.0.0'



dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  lottie: ^2.3.2
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  dio: ^5.1.1
  network_info_plus: ^3.0.2
  device_info_plus: ^8.1.0
  url_launcher: ^6.1.10
  expandable: ^5.0.1
  loading_animation_widget: ^1.2.0+4
  flutter_easyloading: ^3.0.5
  top_snackbar_flutter: ^3.0.0+1
  shimmer: ^2.0.0
  animated_notch_bottom_bar: ^0.0.6
  flutter_neumorphic: ^3.2.0
  top_modal_sheet: ^2.0.1
  custom_sliding_segmented_control: ^1.7.4
  persian_datetime_picker: ^2.5.0
  image_picker: ^0.8.7+5


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.0



flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48



flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icon/


  fonts:
   - family: IRANSans
     fonts:
       - asset: assets/fonts/IRANSans.ttf
